Working sig verification

diff --git a/installer/ubuntu/bootstrap b/installer/ubuntu/bootstrap
--- a/installer/ubuntu/bootstrap
+++ b/installer/ubuntu/bootstrap
@@ -8,8 +8,17 @@
 # directory), $INSTALLERDIR/$DISTRO, $RELEASE, $BOOTSTRAP_RELEASE (if different
 # from $RELEASE), $ARCH, $CAFILE, $VERIFYSIG, and $MIRROR.
 
-PINNEDFINGERPRINTS=('B60EBF2984453C70D74CF478FF914AF0C2B35520' \
-                    'D5C2F9BFCA128BBA22A77218872F702C4D6E25A8')
+PINNED_FINGERPRINTS_DEBOOTSTRAP='
+        B60EBF2984453C70D74CF478FF914AF0C2B35520
+        D5C2F9BFCA128BBA22A77218872F702C4D6E25A8'
+PINNED_FINGERPRINTS_RELEASE='
+	0E4EDE2C7F3E1FC0D033800E64481591B98321F9
+	9FED2BCBDCD29CDF762678CBAED4B06F473041FA
+	ED6D65271AACF0FF15D123036FB2A1C265FFB764
+	A1BD8E9D78F7FE5C3E65D8AF8B48AD6246925553
+	75DDC3C4A499F1A18CB5F3C8CBF8D6FD518E17E1
+	126C0D24BD8A2942CC7DF8AC7638D0442B90D010
+	D21169141CECD440F2EB8DDA9D6D8F6BC857C906'
 
 if [ -n $VERIFYSIG ]; then
     if [ ! "${CACERT:0:1}" = "/" ]; then
@@ -17,12 +26,13 @@ if [ -n $VERIFYSIG ]; then
     fi
 
     # Create the temporary directory and delete it upon exit
-    sigtmp="`mktemp -d --tmpdir=/tmp "${APPLICATION}_pgp"`"
+    sigtmp="`mktemp -d --tmpdir=/tmp "${APPLICATION}_pgp.XXX"`"
     addtrap "rm -rf --one-file-system '$sigtmp'"
 
     # Ensure that the temporary directory has exec+dev, or mount a new tmpfs
     if [ "$NOEXECTMP" = 'y' ]; then
         mount -i -t tmpfs -o 'rw,dev,exec' tmpfs "$sigtmp"
+        chmod 700 "$sigtmp"
         addtrap "umount -l '$sigtmp'"
     fi
 
@@ -37,10 +47,20 @@ keyid-format 0xlong
 with-fingerprint
 EOF
 
-    for key in "${PINNEDFINGERPRINTS[@]}"; do
-        gpg -q --no-default-keyring --homedir $sigtmp --recv-key $key \
+    for key in "$PINNED_FINGERPRINTS_DEBOOTSTRAP"; do
+        gpg -q --no-default-keyring --homedir $sigtmp \
+        --keyring $sigtmp/debootstrap.gpg --recv-key $key \
         || error 2 "Fetching key $key failed."
-        gpg -q --no-default-keyring --homedir $sigtmp -k $key > /dev/null \
+        gpg -q --no-default-keyring --homedir $sigtmp \
+        --keyring $sigtmp/debootstrap.gpg -k $key > /dev/null \
+        || error 2 "Fetched key was not what we requested"
+    done
+    for key in "$PINNED_FINGERPRINTS_RELEASE"; do
+        gpg -q --no-default-keyring --homedir $sigtmp \
+        --keyring $sigtmp/release.gpg --recv-key $key \
+        || error 2 "Fetching key $key failed."
+        gpg -q --no-default-keyring --homedir $sigtmp \
+        --keyring $sigtmp/release.gpg -k $key > /dev/null \
         || error 2 "Fetched key was not what we requested"
     done
 fi
@@ -78,8 +98,8 @@ Check your internet connection or proxy settings and try again.'
             error 1 'Failed to download debootstrap signature.'
         fi
         if ! is_pgp_formatted "$sigtmp/$s" || \
-                ! gpg -q --no-default-keyring --homedir $sigtmp --verify \
-                $sigtmp/$s || \
+                ! gpg -q --no-default-keyring --homedir $sigtmp \
+                --keyring $sigtmp/debootstrap.gpg --verify $sigtmp/$s || \
                 ! grep -q `sha256sum $sigtmp/$f | awk '{ print $1; }'` \
                 $sigtmp/$s; then
             error 1 "Signature verification failed."
@@ -123,9 +143,21 @@ if [ ! -f "$tmp/scripts/$RELEASE" ]; then
     ln -s "$tmp/scripts/$BOOTSTRAP_RELEASE" "$tmp/scripts/$RELEASE"
 fi
 
+debootstrap_arg=''
+if [ -n $VERIFYSIG ]; then
+    debootstrap_arg="--keyring=$sigtmp/release.gpg --force-check-gpg"
+fi
+
 # Grab the release and drop it into the subdirectory
 echo 'Downloading bootstrap files...' 1>&2
 PATH="$newpath" DEBOOTSTRAP_DIR="$tmp" $FAKEROOT \
     "$tmp/debootstrap" --foreign --arch="$ARCH" \
+    $debootstrap_arg \
     "$RELEASE" "$tmp/$subdir" "$MIRROR" 1>&2
+
+if [ -n $VERIFYSIG ]; then
+    mkdir -p $tmp/$subdir/usr/share/keyrings
+    cp -ar $sigtmp/release.gpg \
+        $tmp/$subdir/usr/share/keyrings/debian-archive-keyring.gpg
+fi
 
